config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  root 'chatrooms#index'
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
# frozen_string_literal: true
class Chatroom < ApplicationRecord
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
end

app/models/chatroom_user.rb
# frozen_string_literal: true
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
# frozen_string_literal: true
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
  validates :text, presence: true, length: { maximum: 300 }
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chatroom_users, dependent: :destroy
  has_many :chatrooms, through: :chatroom_users, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :email, :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :avatar]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/chatroom_users_controller.rb
# frozen_string_literal: true
class ChatroomUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom

  def create
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
    redirect_to @chatroom, notice: 'You joined to charoom.'
  end

  def destroy
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
    redirect_to '/', notice: 'You leaved the chatroom.'
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end
end

app/controllers/chatrooms_controller.rb
# frozen_string_literal: true
class ChatroomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set, except: [:index, :new, :create]

  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id)
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
    @message = Message.new
  end

  def new
    @chatroom = Chatroom.new
  end

  def edit; end

  def update
    @chatroom.update_attributes!(chatroom_params)
    redirect_to '/', notice: 'Name of chatroom was changed.'
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.user_id = current_user.id
    if @chatroom.save
      redirect_to '/', notice: 'Chatroom was created.'
    else
      render 'new'
    end
  end

  def destroy
    @chatroom.chatroom_users.destroy_all
    @chatroom.messages.destroy_all
    @chatroom.destroy
    redirect_to '/', notice: 'Chatroom was deleted.'
  end

  private

  def set
    @chatroom = Chatroom.find_by_id(params[:id])
    redirect_to '/' unless @chatroom
  end

  def chatroom_params
    params.require(:chatroom).permit(:name)
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom

  def create
    message = @chatroom.messages.new(message_params)
    message.user = current_user
    MessageRelayJob.perform_later(message)
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end

  def message_params
    params.require(:message).permit(:text)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"   # Green
    when "error"
      "alert-danger"    # Red
    when "alert"
      "alert-warning"   # Yellow
    when "notice"
      "alert-info"      # Blue
    else
      flash_type.to_s
    end
  end
end

app/helpers/chatroom_helper.rb
# frozen_string_literal: true
module ChatroomHelper
end

app/helpers/chatroom_users_helper.rb
# frozen_string_literal: true
module ChatroomUsersHelper
  def joined?(user, chatroom)
    chatroom.chatroom_users.find_by user_id: user.id
  end

  def owner(chatroom)
    User.find_by_id(chatroom.user_id)
  end

  def messages(chatroom)
    chatroom.messages.length
  end
end

app/helpers/messages_helper.rb
# frozen_string_literal: true
module MessagesHelper
end

app/views/chatrooms/_form.html.slim
= simple_form_for @chatroom do |form|
  = form.input :name
  = form.submit

app/views/chatrooms/edit.html.slim
h4 Edit chatroom
= render 'form'

app/views/chatrooms/index.html.slim
br/
h4 All chatrooms
- @chatrooms.each do |chatroom|
  .well 
    div id="chatroom-#{chatroom.id}"
      => image_tag(owner(chatroom).avatar, height: '40', class: 'img-circle') if owner(chatroom).avatar
      b Chatroom:
      - if joined?(current_user, chatroom)
        =< link_to chatroom.name, chatroom_path(chatroom)
      - else
        = chatroom.name
      =< "(#{pluralize(messages(chatroom), 'message')})"
    br/
    =< link_to 'Show', chatroom_path(chatroom)
    - if chatroom.user_id == current_user.id
      =< link_to 'Edit chatroom', edit_chatroom_path(chatroom) 
      =< link_to 'Delete chatroom', chatroom_path(chatroom), method: :delete, data: {confirm: 'Are you sure?'} 
    - if joined?(current_user, chatroom)
      =< link_to 'Leave', chatroom_chatroom_users_path(chatroom), method: :delete
    - else
      =< link_to 'Join', chatroom_chatroom_users_path(chatroom), method: :post   

app/views/chatrooms/new.html.slim
h4 New chatroom
= render 'form'

app/views/chatrooms/show.html.slim
h4 All messages
active[data-chatroom=@chatroom.id]
  = render @messages
- if joined?(current_user, @chatroom)
  = form_for [@chatroom, @message] do |f|
    = f.label :text
    = f.text_field :text, class: "form-control", id: 'text_field', autofocus: true
= link_to 'Back', root_path

app/views/layouts/application.html.slim
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Chat
    = csrf_meta_tags    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = render partial: "shared/flash_messages", flash: flash
      nav.navbar.navbar-default.navbar-fixed-top[role="navigation"]
        a.navbar-brand[href=root_path]
          | Chatrooms
        - if current_user
          => current_user.username
          = image_tag(current_user.avatar, height: '40', class: 'img-circle') if current_user.avatar   
          => link_to 'Edit user', edit_user_registration_path, class: 'btn btn-default'
          = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-default'
      .fluid-container       
        .row-fluid       
          .col-sm-2[style="position: fixed; left: 0;"]
            - if current_user
              h4 = @chatroom.name if @chatroom
              p
                b Joined chatrooms:
              .well
                - current_user.chatrooms.each do |chatroom|
                  div id="list-#{chatroom.id}"
                    = image_tag(owner(chatroom).avatar, height: '30', class: 'img-circle') if owner(chatroom).avatar
                    =< link_to chatroom.name, chatroom
                    =< "(#{pluralize(messages(chatroom), 'message')})"
                  notice[data-chatroom=chatroom.id]
                  hr/
                = link_to 'New chatroom', new_chatroom_path 
          .col-sm-10.col-sm-offset-1        
            = yield
            

app/views/messages/_message.html.slim
.well
  = image_tag(message.user.avatar, height: '40', class: 'img-circle') if message.user.avatar
  b =< message.user.username
  =< message.created_at
  #message_text
    =< message.text

app/views/messages/create.js.erb
$("#new-message").[0].reset();

app/views/shared/_flash_messages.html.slim
- flash.each do |type, message|
  div class=("alert #{bootstrap_class_for(type)} fade in") 
    = message